apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup-sa
  namespace: database-ops
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/postgres-backup-s3-role